In [14]:
# multi dimentional array
#reshape
import numpy as np
np.arange(36).reshape(2,-3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [15]:
np.arange(32).reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [16]:
a = np.array([[1,2],[4,5]])
b= np.array([[7,8],[10,11]])

In [17]:
a+b

array([[ 8, 10],
       [14, 16]])

In [19]:
np.sum((a,b))

48

In [22]:
a[1]+b[1]

array([14, 16])

In [24]:
np.sum(a+b,axis=0) # coloum wise addition

array([22, 26])

In [ ]:
np.sum(a+b,axis=1) # row wise addition

In [25]:
a-b

array([[-6, -6],
       [-6, -6]])

In [26]:
np.sum(a-b)

-24

In [27]:
np.sum(a-b,axis=0)

array([-12, -12])

In [28]:
np.sum(a-b,axis=1)

array([-12, -12])

In [29]:
a*b

array([[ 7, 16],
       [40, 55]])

In [30]:
np.dot(a,b)

array([[27, 30],
       [78, 87]])

In [31]:
a/b

array([[0.14285714, 0.25      ],
       [0.4       , 0.45454545]])

In [32]:
a%b

array([[1, 2],
       [4, 5]], dtype=int32)

In [36]:
#some trigonometry functions
np.sin((a,b))

array([[[ 0.84147098,  0.90929743],
        [-0.7568025 , -0.95892427]],

       [[ 0.6569866 ,  0.98935825],
        [-0.54402111, -0.99999021]]])

In [37]:
np.cos((a,b))

array([[[ 0.54030231, -0.41614684],
        [-0.65364362,  0.28366219]],

       [[ 0.75390225, -0.14550003],
        [-0.83907153,  0.0044257 ]]])

In [38]:
np.tan((a,b))

array([[[   1.55740772,   -2.18503986],
        [   1.15782128,   -3.38051501]],

       [[   0.87144798,   -6.79971146],
        [   0.64836083, -225.95084645]]])

In [39]:
1/np.tan(a)

array([[ 0.64209262, -0.45765755],
       [ 0.86369115, -0.29581292]])

In [40]:
np.std(a)

1.5811388300841898

In [41]:
np.median(a)

3.0

In [42]:
np.exp((a,b))

array([[[2.71828183e+00, 7.38905610e+00],
        [5.45981500e+01, 1.48413159e+02]],

       [[1.09663316e+03, 2.98095799e+03],
        [2.20264658e+04, 5.98741417e+04]]])

In [43]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

In [ ]:
# linear algebra
# 5x + y = 10
# 8x + 2y = 20
a=np.array([[5,1],[8,2]])
b=np.array([10,20])

In [44]:
np.linalg.solve(a,b)

array([[-5., -6.],
       [ 6.,  7.]])

```
5 1
8 2
det=ad-bc
```

In [48]:
round(np.linalg.det(a))

-3.0

In [49]:
np.linalg.eig(a)

(array([-0.46410162,  6.46410162]), array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

**Pandas**
- data analysis
    - we will analysis the data
- data cleaning
    - we will remove the unnecessary data elements/null chatacters
- manupulation
    - we can transform our data into another format/structure

- notations
    - Series
    - DataFrame

In [50]:
import pandas as pd

In [56]:
a=pd.Series([1,2,3,7.8,"c"])

In [57]:
a

0      1
1      2
2      3
3    7.8
4      c
dtype: object

In [58]:
a[0:2]

0    1
1    2
dtype: object

In [60]:
# DataFrames
a=pd.DataFrame([[1,2,3],[4,5,6]])
a

   0  1  2
0  1  2  3
1  4  5  6

In [61]:
import numpy as np
name = np.random.choice(['n1','n2','n3','n4','n5'],20)
marks=np.random.randint(0,100,size=[20])
avg = np.random.choice([20,45,87,39,50],20)

In [65]:
a=list(zip(name,marks,avg))

In [66]:
df=pd.DataFrame(data=a,columns=["name","marks","avg"])
df

   name  marks  avg
0    n1     58   87
1    n5     64   39
2    n5     62   45
3    n4     70   45
4    n5     25   39
5    n1     14   20
6    n5     20   45
7    n1      3   45
8    n1     64   45
9    n4     63   87
10   n5     55   87
11   n2      7   87
12   n2     64   20
13   n1     82   20
14   n1     95   39
15   n5     92   87
16   n3     65   50
17   n2     45   50
18   n1     71   50
19   n3     40   20

In [67]:
df=pd.DataFrame({"name":name,"marks":marks,"avg":avg})
df

   name  marks  avg
0    n1     58   87
1    n5     64   39
2    n5     62   45
3    n4     70   45
4    n5     25   39
5    n1     14   20
6    n5     20   45
7    n1      3   45
8    n1     64   45
9    n4     63   87
10   n5     55   87
11   n2      7   87
12   n2     64   20
13   n1     82   20
14   n1     95   39
15   n5     92   87
16   n3     65   50
17   n2     45   50
18   n1     71   50
19   n3     40   20

In [70]:
b=pd.read_csv("income.csv")
b

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
5,C,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,C,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
7,D,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
8,D,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
9,F,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,G,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,H,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,I,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
13,I,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,I,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,I,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
16,K,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,K,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,L,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
19,M,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
20,M,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
21,M,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
22,M,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
23,M,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
24,M,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
25,M,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
26,M,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
27,N,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
28,N,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
29,N,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
30,N,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
31,N,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
32,N,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
33,N,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,N,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
35,O,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
36,O,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,O,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
38,P,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,R,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
40,S,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
41,S,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
42,T,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,T,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,U,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,V,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [72]:
c=pd.read_csv("file.csv")
c

    name college branch  marks  avg
0  name1      AU    CSE   1000   70
1  name2   Jntuk    ECE   2000   60
2  name3   jntuA    EEE   3000   70
3  name4   JntuV  Civil   2000   60

In [74]:
b

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
5,C,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,C,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
7,D,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
8,D,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
9,F,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,G,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,H,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,I,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
13,I,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,I,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,I,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
16,K,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,K,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,L,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
19,M,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
20,M,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
21,M,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
22,M,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
23,M,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
24,M,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
25,M,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
26,M,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
27,N,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
28,N,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
29,N,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
30,N,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
31,N,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
32,N,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
33,N,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,N,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
35,O,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
36,O,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,O,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
38,P,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,R,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
40,S,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
41,S,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
42,T,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,T,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,U,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,V,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [75]:
b.head()

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607

In [77]:
b.head(2)

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143

In [80]:
b.tail(9)

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
42,T,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,T,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,U,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,V,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [81]:
b.shape

(51, 16)

In [83]:
b["Y2002"].describe()

count    5.100000e+01
mean     1.566034e+06
std      2.464425e+05
min      1.111437e+06
25%      1.374180e+06
50%      1.584734e+06
75%      1.776054e+06
max      1.983285e+06
Name: Y2002, dtype: float64

In [85]:
c.info

<bound method DataFrame.info of     name college branch  marks  avg
0  name1      AU    CSE   1000   70
1  name2   Jntuk    ECE   2000   60
2  name3   jntuA    EEE   3000   70
3  name4   JntuV  Civil   2000   60>

In [89]:
c.values

array([['name1', 'AU', 'CSE', 1000, 70],
       ['name2', 'Jntuk', 'ECE', 2000, 60],
       ['name3', 'jntuA', 'EEE', 3000, 70],
       ['name4', 'JntuV', 'Civil', 2000, 60]], dtype=object)

In [90]:
b["Y2002"]

0     1296530
1     1170302
2     1742027
3     1485531
4     1685349
5     1343824
6     1610512
7     1330403
8     1111437
9     1964626
10    1929009
11    1461570
12    1353210
13    1508356
14    1776918
15    1499269
16    1509054
17    1813878
18    1584734
19    1582720
20    1579713
21    1647582
22    1295635
23    1729921
24    1983285
25    1221316
26    1877154
27    1885081
28    1426117
29    1419776
30    1605532
31    1819239
32    1395149
33    1616742
34    1618807
35    1802132
36    1173918
37    1794912
38    1320191
39    1501744
40    1631522
41    1159037
42    1811867
43    1520591
44    1771096
45    1146902
46    1134317
47    1977749
48    1677347
49    1788920
50    1775190
Name: Y2002, dtype: int64

In [91]:
b.set_index("State")

,Index,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
State,,,,,,,,,,,,,,,
Alabama,A,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
Alaska,A,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
Arizona,A,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
Arkansas,A,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
California,C,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
Colorado,C,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
Connecticut,C,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
Delaware,D,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
District of Columbia,D,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
Florida,F,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
Georgia,G,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
Hawaii,H,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
Idaho,I,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
Illinois,I,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
Indiana,I,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
Iowa,I,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
Kansas,K,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
Kentucky,K,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
Louisiana,L,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
Maine,M,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
Maryland,M,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
Massachusetts,M,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
Michigan,M,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
Minnesota,M,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
Mississippi,M,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
Missouri,M,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
Montana,M,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
Nebraska,N,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
Nevada,N,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
New Hampshire,N,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
New Jersey,N,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
New Mexico,N,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
New York,N,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
North Carolina,N,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
North Dakota,N,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
Ohio,O,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
Oklahoma,O,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
Oregon,O,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
Pennsylvania,P,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
Rhode Island,R,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
South Carolina,S,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
South Dakota,S,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
Tennessee,T,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
Texas,T,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
Utah,U,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
Vermont,V,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
Virginia,V,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
Washington,W,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
West Virginia,W,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
Wisconsin,W,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
Wyoming,W,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [92]:
b

,Index,State,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
0,A,Alabama,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
1,A,Alaska,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
2,A,Arizona,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
3,A,Arkansas,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
4,C,California,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
5,C,Colorado,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
6,C,Connecticut,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
7,D,Delaware,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
8,D,District of Columbia,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
9,F,Florida,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
10,G,Georgia,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
11,H,Hawaii,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
12,I,Idaho,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
13,I,Illinois,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
14,I,Indiana,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
15,I,Iowa,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
16,K,Kansas,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
17,K,Kentucky,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
18,L,Louisiana,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
19,M,Maine,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
20,M,Maryland,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
21,M,Massachusetts,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
22,M,Michigan,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
23,M,Minnesota,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
24,M,Mississippi,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
25,M,Missouri,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
26,M,Montana,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
27,N,Nebraska,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
28,N,Nevada,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
29,N,New Hampshire,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
30,N,New Jersey,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
31,N,New Mexico,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
32,N,New York,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
33,N,North Carolina,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
34,N,North Dakota,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
35,O,Ohio,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
36,O,Oklahoma,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
37,O,Oregon,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
38,P,Pennsylvania,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
39,R,Rhode Island,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
40,S,South Carolina,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
41,S,South Dakota,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
42,T,Tennessee,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
43,T,Texas,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
44,U,Utah,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
45,V,Vermont,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
46,V,Virginia,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
47,W,Washington,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
48,W,West Virginia,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
49,W,Wisconsin,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
50,W,Wyoming,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [93]:
b.set_index("State",inplace=True)

In [94]:
b

,Index,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
State,,,,,,,,,,,,,,,
Alabama,A,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
Alaska,A,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
Arizona,A,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
Arkansas,A,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
California,C,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
Colorado,C,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
Connecticut,C,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
Delaware,D,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
District of Columbia,D,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
Florida,F,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
Georgia,G,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
Hawaii,H,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
Idaho,I,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
Illinois,I,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
Indiana,I,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
Iowa,I,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
Kansas,K,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
Kentucky,K,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
Louisiana,L,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
Maine,M,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
Maryland,M,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
Massachusetts,M,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
Michigan,M,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
Minnesota,M,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
Mississippi,M,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232
Missouri,M,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
Montana,M,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
Nebraska,N,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
Nevada,N,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
New Hampshire,N,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
New Jersey,N,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
New Mexico,N,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
New York,N,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
North Carolina,N,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
North Dakota,N,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
Ohio,O,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
Oklahoma,O,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
Oregon,O,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
Pennsylvania,P,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
Rhode Island,R,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
South Carolina,S,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
South Dakota,S,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
Tennessee,T,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
Texas,T,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
Utah,U,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
Vermont,V,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
Virginia,V,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
Washington,W,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
West Virginia,W,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
Wisconsin,W,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
Wyoming,W,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858

In [104]:
b.sort_values("Y2002",ascending=True)

,Index,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015
State,,,,,,,,,,,,,,,
District of Columbia,D,1111437,1993741,1374643,1827949,1803852,1595981,1193245,1739748,1707823,1353449,1979708,1912654,1782169,1410183
Virginia,V,1134317,1163996,1891068,1853855,1708715,1197698,1803330,1590043,1516758,1171686,1262342,1647032,1706707,1850394
Vermont,V,1146902,1832249,1492704,1579265,1332048,1563537,1123567,1618583,1326369,1792600,1714960,1146278,1282790,1565924
South Dakota,S,1159037,1150689,1660148,1417141,1418586,1279134,1171870,1852424,1554782,1647245,1811156,1147488,1302834,1136443
Alaska,A,1170302,1960378,1818085,1447852,1861639,1465841,1551826,1436541,1629616,1230866,1512804,1985302,1580394,1979143
Oklahoma,O,1173918,1334639,1663622,1798714,1312574,1708245,1256746,1853142,1673831,1822933,1674707,1900523,1956742,1307678
Missouri,M,1221316,1858368,1773451,1573967,1374863,1486197,1735099,1800620,1164202,1425363,1800052,1698105,1767835,1996005
Michigan,M,1295635,1149931,1601027,1340716,1729449,1567494,1990431,1575185,1267626,1274673,1709853,1815596,1965196,1646634
Alabama,A,1296530,1317711,1118631,1492583,1107408,1440134,1945229,1944173,1237582,1440756,1186741,1852841,1558906,1916661
Pennsylvania,P,1320191,1446723,1218591,1122030,1971479,1563062,1274168,1571032,1433835,1483292,1290329,1475344,1931500,1668232
Delaware,D,1330403,1268673,1706751,1403759,1441351,1300836,1762096,1553585,1370984,1318669,1984027,1671279,1803169,1627508
Colorado,C,1343824,1878473,1886149,1236697,1871471,1814218,1875146,1752387,1913275,1665877,1491604,1178355,1383978,1330736
Idaho,I,1353210,1438538,1739154,1541015,1122387,1772050,1335481,1748608,1436809,1456340,1643855,1312561,1713718,1757171
New York,N,1395149,1611371,1170675,1446810,1426941,1463171,1732098,1426216,1604531,1683687,1500089,1718837,1619033,1367705
New Hampshire,N,1419776,1854370,1195119,1990062,1645430,1286967,1762936,1763211,1265642,1704297,1131298,1197576,1242623,1963313
Nevada,N,1426117,1114500,1119707,1758830,1694526,1765826,1903270,1231480,1526066,1143343,1980195,1283813,1225348,1903804
Hawaii,H,1461570,1200280,1213993,1245931,1459383,1430465,1919423,1928416,1330509,1902816,1695126,1517184,1948108,1150882
Arkansas,A,1485531,1994927,1119299,1947979,1669191,1801213,1188104,1628980,1669295,1928238,1216675,1591896,1360959,1329341
Iowa,I,1499269,1444576,1576367,1388924,1554813,1452911,1317983,1150783,1751389,1992996,1501879,1173694,1431705,1641866
Rhode Island,R,1501744,1942942,1266657,1961923,1835983,1234040,1151409,1993136,1983569,1781016,1909119,1531212,1990412,1611730
Illinois,I,1508356,1527440,1493029,1261353,1540274,1747614,1871645,1658551,1422021,1751422,1696729,1915435,1645465,1583516
Kansas,K,1509054,1290700,1522230,1532094,1104256,1863278,1949478,1561528,1550433,1465812,1882929,1410249,1930090,1385528
Texas,T,1520591,1310777,1957713,1907326,1873544,1655483,1785986,1827503,1447457,1978374,1882532,1698698,1646508,1705322
Maryland,M,1579713,1404700,1849798,1397738,1310270,1789128,1112765,1967225,1486246,1872327,1175819,1314343,1979529,1569566
Maine,M,1582720,1678622,1208496,1912040,1438549,1330014,1295877,1969163,1627262,1706080,1437088,1318546,1116792,1529233
Louisiana,L,1584734,1110625,1868456,1751920,1233709,1920301,1185085,1124853,1498662,1210385,1234234,1287663,1908602,1403857
New Jersey,N,1605532,1141514,1613550,1181452,1541327,1156804,1568034,1357418,1443718,1390010,1202326,1100990,1850165,1183568
Connecticut,C,1610512,1232844,1181949,1518933,1841266,1976976,1764457,1972730,1968730,1945524,1228529,1582249,1503156,1718072
North Carolina,N,1616742,1292223,1482792,1532347,1158716,1827420,1267737,1116168,1791535,1553750,1472258,1104893,1596452,1229085
North Dakota,N,1618807,1510193,1876940,1443172,1425030,1868788,1720352,1671468,1534571,1271132,1430978,1529024,1563898,1604118
South Carolina,S,1631522,1803455,1425193,1458191,1538731,1825195,1250499,1864685,1345102,1116203,1532332,1591735,1188417,1110655
Massachusetts,M,1647582,1686259,1620601,1777250,1531641,1380529,1978904,1567651,1761048,1658538,1482203,1731917,1669749,1963337
West Virginia,W,1677347,1380662,1176100,1888948,1922085,1740826,1238174,1539322,1539603,1872519,1462137,1683127,1204344,1198791
California,C,1685349,1675807,1889570,1480280,1735069,1812546,1487315,1663809,1624509,1639670,1921845,1156536,1388461,1644607
Minnesota,M,1729921,1675204,1903907,1561839,1985692,1148621,1328133,1890633,1995304,1575533,1910216,1972021,1515366,1864553
Arizona,A,1742027,1968140,1377583,1782199,1102568,1109382,1752886,1554330,1300521,1130709,1907284,1363279,1525866,1647724
Utah,U,1771096,1195861,1979395,1241662,1437456,1859416,1939284,1915865,1619186,1288285,1108281,1123353,1801019,1729273
Wyoming,W,1775190,1498098,1198212,1881688,1750527,1523124,1587602,1504455,1282142,1881814,1673668,1994022,1204029,1853858
Indiana,I,1776918,1734104,1269927,1204117,1848073,1129546,1139551,1883976,1999102,1559924,1905760,1129794,1988394,1467614
Wisconsin,W,1788920,1518578,1289663,1436888,1251678,1721874,1980167,1901394,1648755,1940943,1729177,1510119,1701650,1846238
Oregon,O,1794912,1726665,1805445,1133510,1502242,1419251,1482786,1862351,1103794,1935687,1905378,1522129,1509171,1893515
Ohio,O,1802132,1648498,1441386,1670280,1534888,1314824,1516621,1511460,1585465,1887714,1227303,1840898,1880804,1573117
Tennessee,T,1811867,1485909,1974179,1157059,1786132,1399191,1826406,1326460,1231739,1469785,1849041,1560887,1349173,1162164
Kentucky,K,1813878,1448846,1800760,1250524,1137913,1911227,1301848,1956681,1350895,1512894,1916616,1878271,1722762,1913350
New Mexico,N,1819239,1226057,1935991,1124400,1723493,1475985,1237704,1820856,1801430,1653384,1475715,1623388,1533494,1868612
Montana,M,1877154,1540099,1332722,1273327,1625721,1983568,1251742,1592690,1350619,1520064,1185225,1465705,1110394,1125903
Nebraska,N,1885081,1309769,1425527,1240465,1500594,1278272,1140598,1270585,1128711,1187207,1569665,1690920,1459243,1802211
Georgia,G,1929009,1541565,1810773,1779091,1326846,1223770,1773090,1630325,1145473,1851245,1850111,1887157,1259353,1725470
Florida,F,1964626,1468852,1419738,1362787,1339608,1278550,1756185,1818438,1198403,1497051,1131928,1107448,1407784,1170389
Washington,W,1977749,1687136,1199490,1163092,1334864,1621989,1545621,1555554,1179331,1150089,1775787,1273834,1387428,1377341
Mississippi,M,1983285,1292558,1631325,1943311,1354579,1731643,1428291,1568049,1383227,1629132,1988270,1907777,1649668,1991232